# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='panel_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
