# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelstatus',
            name='apartment',
            field=models.IntegerField(default=0),
        ),
    ]
