# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170409_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelstatus',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
